version: '3.8'

services:
  mongo:
    image: mongo:latest
    container_name: task_05_mongo
    volumes:
      - mongo-data:/data/db
    ports:
      - "27017:27017"

  node-api:
    build: .
    container_name: task_05_node_api
    ports:
      - "3000:3000"
    environment:
      - MONGO_URL=mongodb://mongo:27017/db
    depends_on:
      - mongo

volumes:
  mongo-data:
