// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PropFinderApi.Contexts;

#nullable disable

namespace PropFinderApi.Migrations
{
    [DbContext(typeof(PropFinderDbContext))]
    partial class PropFinderDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PropFinderApi.Models.ContactLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("BuyerEmail")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("BuyerId")
                        .HasColumnType("uuid");

                    b.Property<string>("BuyerPhoneNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ListerEmail")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("ListerId")
                        .HasColumnType("uuid");

                    b.Property<string>("ListerName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ListerPhoneNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("PropertyId")
                        .HasColumnType("uuid");

                    b.HasKey("Id")
                        .HasName("PK_ContactLog");

                    b.HasIndex("BuyerId");

                    b.HasIndex("ListerId");

                    b.HasIndex("PropertyId");

                    b.ToTable("ContactLogs");
                });

            modelBuilder.Entity("PropFinderApi.Models.DiscountCode", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("DiscountValue")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("FromDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsPercentage")
                        .HasColumnType("boolean");

                    b.Property<int>("ListerUsageCount")
                        .HasColumnType("integer");

                    b.Property<int?>("MaxListerLimit")
                        .HasColumnType("integer");

                    b.Property<DateTime>("ToDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("DiscountCodes");
                });

            modelBuilder.Entity("PropFinderApi.Models.DiscountCodeOptions", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("DiscountCodeId")
                        .HasColumnType("uuid");

                    b.Property<decimal?>("MaxPrice")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("MinPrice")
                        .HasColumnType("numeric");

                    b.Property<string>("PurposeOfListing")
                        .HasColumnType("text");

                    b.Property<string>("TypeOfProperty")
                        .HasColumnType("text");

                    b.HasKey("Id")
                        .HasName("PK_DiscountCode");

                    b.HasIndex("DiscountCodeId");

                    b.ToTable("DiscountCodeOptions");
                });

            modelBuilder.Entity("PropFinderApi.Models.FeatureApplicability", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AppliesToPurpose")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("AppliesToType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("FeatureId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.HasKey("Id")
                        .HasName("PK_FeatureApplicability");

                    b.HasIndex("FeatureId");

                    b.ToTable("FeatureApplicabilities");
                });

            modelBuilder.Entity("PropFinderApi.Models.FeatureMaster", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DataType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("FilterMode")
                        .HasColumnType("integer");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id")
                        .HasName("PK_FeatureMaster");

                    b.ToTable("FeatureMasters");
                });

            modelBuilder.Entity("PropFinderApi.Models.FeatureOption", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("FeatureId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id")
                        .HasName("PK_FeatureOption");

                    b.HasIndex("FeatureId");

                    b.ToTable("FeatureOptions");
                });

            modelBuilder.Entity("PropFinderApi.Models.ListerProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AgencyName")
                        .HasColumnType("text");

                    b.Property<string>("BusinessPhoneNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsVerifiedAgent")
                        .HasColumnType("boolean");

                    b.Property<string>("LicenseNumber")
                        .HasColumnType("text");

                    b.Property<string>("ProfilePictureUrl")
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id")
                        .HasName("PK_ListerProfile");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("ListerProfiles");
                });

            modelBuilder.Entity("PropFinderApi.Models.Property", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("AreaSqFt")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<Guid>("ListerId")
                        .HasColumnType("uuid");

                    b.Property<string>("ListerType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ListingPurpose")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric");

                    b.Property<string>("PropertyType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id")
                        .HasName("PK_Property");

                    b.HasIndex("ListerId");

                    b.ToTable("Properties");
                });

            modelBuilder.Entity("PropFinderApi.Models.PropertyDiscountCode", b =>
                {
                    b.Property<Guid>("PropertyId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("DiscountCodeId")
                        .HasColumnType("uuid");

                    b.HasKey("PropertyId", "DiscountCodeId")
                        .HasName("PK_PropertyDiscountCode");

                    b.HasIndex("DiscountCodeId");

                    b.ToTable("PropertyDiscountCodes");
                });

            modelBuilder.Entity("PropFinderApi.Models.PropertyFeature", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("FeatureId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("OptionId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("PropertyId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("Id")
                        .HasName("PK_PropertyFeature");

                    b.HasIndex("FeatureId");

                    b.HasIndex("OptionId");

                    b.HasIndex("PropertyId");

                    b.ToTable("PropertyFeatures");
                });

            modelBuilder.Entity("PropFinderApi.Models.PropertyImage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsPrimary")
                        .HasColumnType("boolean");

                    b.Property<Guid>("PropertyId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id")
                        .HasName("PK_PropertyImage");

                    b.HasIndex("PropertyId");

                    b.ToTable("PropertyImages");
                });

            modelBuilder.Entity("PropFinderApi.Models.PropertyLocation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal?>("Latitude")
                        .HasColumnType("numeric");

                    b.Property<string>("Locality")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal?>("Longitude")
                        .HasColumnType("numeric");

                    b.Property<Guid>("PropertyId")
                        .HasColumnType("uuid");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id")
                        .HasName("PK_PropertyLocation");

                    b.HasIndex("PropertyId")
                        .IsUnique();

                    b.ToTable("PropertyLocations");
                });

            modelBuilder.Entity("PropFinderApi.Models.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ReplacedByToken")
                        .HasColumnType("text");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id")
                        .HasName("PK_RefreshToken");

                    b.HasIndex("UserId");

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("PropFinderApi.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id")
                        .HasName("PK_User");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("PropFinderApi.Models.ContactLog", b =>
                {
                    b.HasOne("PropFinderApi.Models.User", "Buyer")
                        .WithMany("ContactRequestsMade")
                        .HasForeignKey("BuyerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_ContactLog_Buyer");

                    b.HasOne("PropFinderApi.Models.User", "Lister")
                        .WithMany("ContactRequestsReceived")
                        .HasForeignKey("ListerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_ContactLog_Lister");

                    b.HasOne("PropFinderApi.Models.Property", "Property")
                        .WithMany("ContactRequests")
                        .HasForeignKey("PropertyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_ContactLog_Property");

                    b.Navigation("Buyer");

                    b.Navigation("Lister");

                    b.Navigation("Property");
                });

            modelBuilder.Entity("PropFinderApi.Models.DiscountCodeOptions", b =>
                {
                    b.HasOne("PropFinderApi.Models.DiscountCode", "DiscountCode")
                        .WithMany("Options")
                        .HasForeignKey("DiscountCodeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DiscountCode");
                });

            modelBuilder.Entity("PropFinderApi.Models.FeatureApplicability", b =>
                {
                    b.HasOne("PropFinderApi.Models.FeatureMaster", "Feature")
                        .WithMany("Applicability")
                        .HasForeignKey("FeatureId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_FeatureAvailability_Feature");

                    b.Navigation("Feature");
                });

            modelBuilder.Entity("PropFinderApi.Models.FeatureOption", b =>
                {
                    b.HasOne("PropFinderApi.Models.FeatureMaster", "Feature")
                        .WithMany("Options")
                        .HasForeignKey("FeatureId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_FeatureOption_Feature");

                    b.Navigation("Feature");
                });

            modelBuilder.Entity("PropFinderApi.Models.ListerProfile", b =>
                {
                    b.HasOne("PropFinderApi.Models.User", "User")
                        .WithOne("ListerProfile")
                        .HasForeignKey("PropFinderApi.Models.ListerProfile", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_ListerProfile_User");

                    b.Navigation("User");
                });

            modelBuilder.Entity("PropFinderApi.Models.Property", b =>
                {
                    b.HasOne("PropFinderApi.Models.User", "Lister")
                        .WithMany("Properties")
                        .HasForeignKey("ListerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Property_Lister");

                    b.Navigation("Lister");
                });

            modelBuilder.Entity("PropFinderApi.Models.PropertyDiscountCode", b =>
                {
                    b.HasOne("PropFinderApi.Models.DiscountCode", "DiscountCode")
                        .WithMany("PropertyDiscountCodes")
                        .HasForeignKey("DiscountCodeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PropFinderApi.Models.Property", "Property")
                        .WithMany("PropertyDiscountCodes")
                        .HasForeignKey("PropertyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DiscountCode");

                    b.Navigation("Property");
                });

            modelBuilder.Entity("PropFinderApi.Models.PropertyFeature", b =>
                {
                    b.HasOne("PropFinderApi.Models.FeatureMaster", "Feature")
                        .WithMany()
                        .HasForeignKey("FeatureId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_PropertyFeature_Feature");

                    b.HasOne("PropFinderApi.Models.FeatureOption", "Option")
                        .WithMany()
                        .HasForeignKey("OptionId")
                        .HasConstraintName("FK_PropertyFeature_FeatureOption");

                    b.HasOne("PropFinderApi.Models.Property", "Property")
                        .WithMany("Features")
                        .HasForeignKey("PropertyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_PropertyFeature_Property");

                    b.Navigation("Feature");

                    b.Navigation("Option");

                    b.Navigation("Property");
                });

            modelBuilder.Entity("PropFinderApi.Models.PropertyImage", b =>
                {
                    b.HasOne("PropFinderApi.Models.Property", "Property")
                        .WithMany("PropertyImages")
                        .HasForeignKey("PropertyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_PropertyImage_Property");

                    b.Navigation("Property");
                });

            modelBuilder.Entity("PropFinderApi.Models.PropertyLocation", b =>
                {
                    b.HasOne("PropFinderApi.Models.Property", "Property")
                        .WithOne("Location")
                        .HasForeignKey("PropFinderApi.Models.PropertyLocation", "PropertyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_PropertyLocation_Property");

                    b.Navigation("Property");
                });

            modelBuilder.Entity("PropFinderApi.Models.RefreshToken", b =>
                {
                    b.HasOne("PropFinderApi.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_RefreshToken_User");

                    b.Navigation("User");
                });

            modelBuilder.Entity("PropFinderApi.Models.DiscountCode", b =>
                {
                    b.Navigation("Options");

                    b.Navigation("PropertyDiscountCodes");
                });

            modelBuilder.Entity("PropFinderApi.Models.FeatureMaster", b =>
                {
                    b.Navigation("Applicability");

                    b.Navigation("Options");
                });

            modelBuilder.Entity("PropFinderApi.Models.Property", b =>
                {
                    b.Navigation("ContactRequests");

                    b.Navigation("Features");

                    b.Navigation("Location")
                        .IsRequired();

                    b.Navigation("PropertyDiscountCodes");

                    b.Navigation("PropertyImages");
                });

            modelBuilder.Entity("PropFinderApi.Models.User", b =>
                {
                    b.Navigation("ContactRequestsMade");

                    b.Navigation("ContactRequestsReceived");

                    b.Navigation("ListerProfile");

                    b.Navigation("Properties");
                });
#pragma warning restore 612, 618
        }
    }
}
