using Microsoft.AspNetCore.Http;
using QuestPDF.Fluent;
using QuestPDF.Helpers;
using QuestPDF.Infrastructure;
using ChienVHShopOnline.Models.DTOs;


namespace ChienVHShopOnline.Helpers
{

    public class OrderPdfGenerator
    {
        public static byte[] Generate(OrderResponseDto order)
        {
            return Document.Create(container =>
            {
                container.Page(page =>
                {
                    page.Margin(30);
                    page.Size(PageSizes.A4);
                    page.PageColor(Colors.White);
                    page.DefaultTextStyle(x => x.FontSize(12));

                    page.Header().Text($"Order Summary - #{order.Id}")
                                .FontSize(18).Bold().AlignCenter();

                    page.Content().PaddingVertical(10).Column(col =>
                    {
                        // Order Info
                        col.Item().Text($"Order Name: {order.OrderName}");
                        col.Item().Text($"Order Date: {order.OrderDate:yyyy-MM-dd}");
                        col.Item().Text($"Payment Type: {order.PaymentType}");
                        col.Item().Text($"Status: {order.Status}");

                        col.Item().PaddingVertical(10).LineHorizontal(1);

                        // Customer Info
                        col.Item().Text("Customer Information").Bold().FontSize(14);
                        col.Item().Text($"Name: {order.CustomerName}");
                        col.Item().Text($"Phone: {order.CustomerPhone}");
                        col.Item().Text($"Email: {order.CustomerEmail}");
                        col.Item().Text($"Address: {order.CustomerAddress}");

                        col.Item().PaddingVertical(10).LineHorizontal(1);

                        // Order Details Table
                        col.Item().Text("Order Details").Bold().FontSize(14);

                        col.Item().Table(table =>
                        {
                            table.ColumnsDefinition(columns =>
                            {
                                columns.ConstantColumn(40);  // S/N
                                columns.RelativeColumn(2);   // Product
                                columns.RelativeColumn();    // Quantity
                                columns.RelativeColumn();    // Price
                                columns.RelativeColumn();    // Total
                            });

                            table.Header(header =>
                            {
                                header.Cell().Text("#").Bold();
                                header.Cell().Text("Product").Bold();
                                header.Cell().Text("Qty").Bold();
                                header.Cell().Text("Unit Price").Bold();
                                header.Cell().Text("Total").Bold();
                            });

                            int i = 1;
                            foreach (var item in order.OrderDetails)
                            {
                                table.Cell().Text(i++.ToString());
                                table.Cell().Text(item.ProductName);
                                table.Cell().Text(item.Quantity.ToString());
                                table.Cell().Text($"{item.Price:C}");
                                table.Cell().Text($"{item.Quantity * item.Price:C}");
                            }
                        });

                        double total = order.OrderDetails.Sum(x => x.Quantity * (x.Price ?? 0)) ?? 0;

                        col.Item().PaddingTop(10).AlignRight().Text($"Total: {total:C}").Bold();
                    });

                    page.Footer().AlignCenter().Text("Generated by ChienVH Shop Online");
                });
            }).GeneratePdf();
        }
    }
}
